version: '3.8'

x-flyway: &flyway
  image: flyway/flyway:9.4.0
  volumes:
    - ./db/sql:/flyway/sql
    - ./db/conf:/flyway/conf
  depends_on:
    - db

services:
  flyway-clean:
    <<: *flyway
    command: clean

  flyway-migrate:
    <<: *flyway
    command: migrate

  flyway-info:
    <<: *flyway
    command: info

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    container_name: db